### ISSUE TITLE
Bug: No jobs available on Jobs page

### ISSUE THREAD

**Issue by mustafanawabi** [base-org/web#451] opened 2024-04-20 18:42 UTC
### Describe the bug

The jobs page is empty even though jobs are available

### Steps

1. Go to https://www.base.org/
2. Press About > Jobs
3. The page is empty with no jobs available, even though there are jobs available
4. Refresh the page
5. Jobs are available

### Expected behavior

The jobs page should load jobs if available

### Additional info

Navigating to jobs page:

<img width="1308" alt="Screen Shot 2024-04-20 at 2 41 38 PM" src="https://github.com/base-org/web/assets/4382148/1ac6ab5a-76a1-4b93-aaf7-3678a6a31f01">

After refresh:
<img width="1292" alt="Screen Shot 2024-04-20 at 2 41 44 PM" src="https://github.com/base-org/web/assets/4382148/fec10e54-839b-4788-9413-fef6ff8ef968">

### Environment

Chrome

**Comment by wbnns** [comment] 2024-04-24 00:00
@mustafanawabi 

Heya! Are you able to replicate this issue? I'm currently unable to get the page to load without showing jobs (as reported). Seems to be working ok in both my regular tab as well as a private one.

**Comment by carlaiau** [comment] 2024-04-26 00:10
@wbnns @mustafanawabi in my ad-hoc testing the issue is only present whilst the NftBanner is shown. Once the NftBanner has been hidden then the issue is rectified. That being said the banner only recently made it into the code base so that doesn't explain this issue existing prior to this amendment, but you should be able to replicate via opening the site incognito to get the NftBanner back.

**Comment by wbnns** [comment] 2024-04-26 02:03
@carlaiau Thanks for the tip!

**Comment by wbnns** [comment] 2024-05-22 20:48
I haven't seen any additional reports of this issue in recent weeks; closing for now but will reopen if we observe a rise in reports.

**Closed by wbnns** 2024-05-22 20:48 UTC
Labels: type: bug
